### ISSUE TITLE
The code for reproducing EP task results

### ISSUE THREAD

**Issue by sagnik** [bvanaken/explain-BERT-QA#1]
Hi, the paper is great, thanks for the code! 

I am trying to find the part where the edge probing task results are produced (figure 2 of the paper). Could you please point me to that?

**Comment by bvanaken** [comment]
Hi, thanks for reaching out!
We have created the edge probing results with the jiant probing framework from Wang et al. The version we used back then is available here: https://github.com/nyu-mll/jiant-v1-legacy/tree/master/probing. You can create the data for our additional QA-specific tasks with the code in [probing-tasks](https://github.com/bvanaken/explain-BERT-QA/tree/master/probing-tasks).
